In [1]:
import numpy as np

In [2]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [5]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [6]:
np.arange(1,100,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [9]:
np.arange(3,22,3)

array([ 3,  6,  9, 12, 15, 18, 21])

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.zeros(100,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [15]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [18]:
np.random.rand(3,5) 

array([[0.84849956, 0.27794966, 0.49790376, 0.65327532, 0.08614647],
       [0.60020632, 0.56999493, 0.97449083, 0.42602484, 0.28035675],
       [0.81867854, 0.58120114, 0.04980704, 0.09886652, 0.30414681]])

In [19]:
np.random.randn(3,5)

array([[ 0.91747551,  0.8972402 , -0.30745313, -1.22418383,  0.58748861],
       [-0.66250314, -0.53480428, -0.17121886, -0.30434584,  0.2322609 ],
       [ 0.65837389,  0.84226436,  0.41093757, -1.40013667,  0.41488974]])

In [21]:
np.random.randint(0,10,50)

array([3, 1, 1, 1, 9, 7, 8, 4, 7, 6, 8, 7, 6, 8, 6, 5, 5, 9, 1, 2, 6, 7,
       6, 9, 0, 9, 8, 5, 6, 8, 9, 3, 9, 9, 7, 5, 3, 2, 2, 9, 8, 3, 1, 1,
       7, 0, 2, 1, 3, 7])

In [28]:
sample_array=np.arange(0,30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [29]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [30]:
sample_array.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [31]:
sample_array.reshape(4,6)

ValueError: cannot reshape array of size 30 into shape (4,6)

In [33]:
sample_array[0]

0

In [34]:
sample_array[6]

6

In [35]:
sample_array[60]

IndexError: index 60 is out of bounds for axis 0 with size 30

In [36]:
sample_array[5:10]

array([5, 6, 7, 8, 9])

In [37]:
sample_array[0]=100

In [38]:
sample_array

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [41]:
sample_matrix=np.array([[1,7,8,4,2],[4,9,3,2,87],[32,21,54,61,5]])
sample_matrix

array([[ 1,  7,  8,  4,  2],
       [ 4,  9,  3,  2, 87],
       [32, 21, 54, 61,  5]])

In [42]:
sample_matrix[1,2]

3

In [43]:
sample_matrix[2,3]

61

In [45]:
sample_matrix[2,:]

array([32, 21, 54, 61,  5])

In [47]:
sample_matrix[3,2]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [48]:
sample_matrix(:,(3,2))

SyntaxError: invalid syntax (3984879163.py, line 1)

In [49]:
sample_matrix[:,[3,1]]

array([[ 4,  7],
       [ 2,  9],
       [61, 21]])

In [50]:
sample_array=np.arange(1,8)
sample_array

array([1, 2, 3, 4, 5, 6, 7])

In [51]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14])

In [52]:
np.max(sample_array)

7

In [53]:
np.min(sample_array)

1

In [54]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131])

In [55]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015])

In [56]:
np.exp(sample_array)

array([   2.71828183,    7.3890561 ,   20.08553692,   54.59815003,
        148.4131591 ,  403.42879349, 1096.63315843])

In [57]:
np.mean(sample_array)

4.0

In [58]:
np.var(sample_array)

4.0

In [61]:
np.std(sample_array)

2.0

In [62]:
np.square(sample_array)

array([ 1,  4,  9, 16, 25, 36, 49])